# Generated by Django 5.1.15 on 2026-04-12 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='office',
            field=models.CharField(choices=[('registrar', 'Registrar Office'), ('document', 'Document Services')], default='registrar', max_length=50, verbose_name='School Office'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='purpose',
            field=models.CharField(choices=[('tor_request', 'Transcript of Records (TOR) Request'), ('document_request', 'Document Request'), ('certification', 'Certification / Certificate of Enrollment'), ('good_moral', 'Good Moral Certificate'), ('diploma_request', 'Diploma / Graduation Documents'), ('grade_inquiry', 'Grade / Academic Inquiry'), ('other', 'Other Concern')], max_length=50, verbose_name='Purpose / Concern'),
        ),
    ]
